defaults: # for loading the default config
  - task: change_detection
    optional: True
  - model_type: SiamKPConvWithPriorAgreement
    optional: True
  - dataset: HKCDPair
    optional: True

  - visualization: default
  - lr_scheduler: exponential
  - training: defaultHKCD

  - debugging: default.yaml
  - models: ${defaults.0.task}/${defaults.1.model_type}
  - data: ${defaults.0.task}/${defaults.2.dataset}
  - hydra/job_logging: custom
  - hydra/output: custom

job_name: SiamKPConvAgreement-${now:%Y-%m-%d}
model_name: SiamKPConvWithPriorAgreement
update_lr_scheduler_on: "on_epoch"
selection_stage: ""
pretty_print: True
eval_frequency: 1
output_dir: "" # Path to the output directory

tracker_options:
  full_pc: False
  full_res: False
  make_submission: False
  track_boxes: False

hydra:
  run:
    dir: ${output_dir}/train_${model_name}_${now:%Y-%m-%d_%H-%M-%S}
  job_logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      detailed:
        format: "[%(asctime)s.%(msecs)03d][%(levelname).1s]%(name)s: %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%S"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: detailed
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: detailed
        filename: ${hydra.job.name}.log
    root:
      level: INFO
      handlers: [console, file]